version: "3"
services:
  master:
    image: jenkins/jenkins
    ports:
    - "80:8080"
    - "50000:50000"
    environment:
      JAVA_OPTS: "-Djenkins.install.runSetupWizard=false -Xmx2048m"
    volumes:
    - jenkins-master:/var/jenkins_home/master
    - "./init.groovy.d/plugins.groovy:/var/jenkins_home/init.groovy.d/plugins.groovy"
    - "./init.groovy.d/security.groovy:/var/jenkins_home/init.groovy.d/security.groovy"
    - "./init.groovy.d/slaves.groovy:/var/jenkins_home/init.groovy.d/slaves.groovy"
    - "./init.groovy.d/workflow.groovy:/var/jenkins_home/init.groovy.d/workflow.groovy"

  slave-1:
    image: jenkinsci/jnlp-slave
    environment:
      JAVA_OPTS: "-Xmx2048m"
      JENKINS_URL: "http://master:8080"
      JENKINS_AGENT_NAME: "slave-1"
    command: "/connect_to_slave.sh"
    volumes:
    - jenkins-slave-1:/home/jenkins/agent
    - "./connect_to_slave.sh:/connect_to_slave.sh"
    - "./get_slave-1_secret.groovy:/get_slave-1_secret.groovy"

  slave-2:
    image: jenkinsci/jnlp-slave
    environment:
      JAVA_OPTS: "-Xmx2048m"
      JENKINS_URL: "http://master:8080"
      JENKINS_AGENT_NAME: "slave-2"
      JENKINS_RETRY: "10"
    command: "/connect_to_slave.sh"
    volumes:
    - jenkins-slave-2:/home/jenkins/agent
    - "./connect_to_slave.sh:/connect_to_slave.sh"
    - "./get_slave-2_secret.groovy:/get_slave-2_secret.groovy"

volumes:
  jenkins-master:
  jenkins-slave-1:
  jenkins-slave-2:
