---
- copy:
    src:  docker_defaults
    dest: /etc/default/docker

- service:
    name: docker
    state: restarted

- file:
    path: /var/jenkins/init.groovy.d
    state: directory

- copy:
    src:  docker.groovy
    dest: /var/jenkins/init.groovy.d/docker.groovy

- copy:
    src:  jnlp.groovy
    dest: /var/jenkins/init.groovy.d/jnlp.groovy

- copy:
    src:  plugins.groovy
    dest: /var/jenkins/init.groovy.d/plugins.groovy

- copy:
    src:  security.groovy
    dest: /var/jenkins/init.groovy.d/security.groovy

- copy:
    src:  workflow.groovy
    dest: /var/jenkins/init.groovy.d/workflow.groovy

- docker_container:
    name: jenkins
    image: jenkins/jenkins
    state: started
    restart: yes
    restart_policy: on-failure
    ports:
      - "80:8080"
      - "50000:50000"
    env:
      JAVA_OPTS: "-Djenkins.install.runSetupWizard=false -Xmx2048m"
    volumes:
      - "/var/jenkins/init.groovy.d/:/var/jenkins_home/init.groovy.d/"
