---
- file:
    path: /var/jenkins/init.groovy.d
    state: directory

- copy:
    src:  plugins.groovy
    dest: /var/jenkins/init.groovy.d/plugins.groovy

- copy:
    src:  security.groovy
    dest: /var/jenkins/init.groovy.d/security.groovy

- copy:
    src:  slaves.groovy
    dest: /var/jenkins/init.groovy.d/slaves.groovy

- copy:
    src:  workflow.groovy
    dest: /var/jenkins/init.groovy.d/workflow.groovy


- docker_container:
    name: jenkins
    image: jenkins/jenkins
    state: started
    restart: yes
    restart_policy: on-failure
    ports:
      - "80:8080"
      - "50000:50000"
    env:
      JAVA_OPTS: "-Djenkins.install.runSetupWizard=false -Xmx2048m"
    volumes:
      - "/var/jenkins/init.groovy.d/plugins.groovy:/var/jenkins_home/init.groovy.d/plugins.groovy"
      - "/var/jenkins/init.groovy.d/security.groovy:/var/jenkins_home/init.groovy.d/security.groovy"
      - "/var/jenkins/init.groovy.d/slaves.groovy:/var/jenkins_home/init.groovy.d/slaves.groovy"
      - "/var/jenkins/init.groovy.d/workflow.groovy:/var/jenkins_home/init.groovy.d/workflow.groovy"